/** `@/view` 的唯一出口：坐标的算术真相（`geometry.js`）与把它画出来的 `Layout` + 各组件 */

export {
  BORDER_COLUMNS,
  BORDER_LEFT_COLUMN,
  BORDER_ROWS,
  MAIN_MIN_WIDTH,
  MAIN_TEXT_X,
  MIN_TERMINAL_COLUMNS,
  NOTICE_ROWS,
  PALETTE_MAX_RATIO,
  PROMPT_COLUMNS,
  SESSION_CLOSE_COLUMNS,
  SESSION_ROWS,
  SIDEBAR_CLOSE_MIN_NAME,
  SIDEBAR_GAP,
  SIDEBAR_MAX_WIDTH,
  SIDEBAR_MIN_WIDTH,
  SIDEBAR_TEXT_X,
  SIDEBAR_TOP_MARGIN,
  SIDEBAR_WIDTH,
  STATUS_LINE_HEIGHT,
  WINDOW_CLOSE_COLUMNS,
  caretFromColumn,
  caretFromWrappedPoint,
  caretRowOf,
  geometry,
  hitTest,
  sidebarWidthBounds,
  wrapInput,
  type Geometry,
  type GeometryInput,
  type Rect,
  type WrappedRow,
} from "./geometry.js";
export { Layout } from "./layout.js";
export type {
  LayoutProps,
  PaletteRowView,
  PaletteView,
  SessionRow,
  WindowRow,
  WindowView,
} from "./components/index.js";