/** `@/lib` 的唯一出口：零 IO 的那一半（排版、着色判据、几何、行模型、输入串、失败词汇、收窄组合子） */

export {
  arr,
  bool,
  nullable,
  num,
  obj,
  oneOf,
  opaque,
  optional,
  str,
  strArr,
  type Decode,
} from "./decode.js";
export {
  LOCAL_REQUEST,
  TuiError,
  isRetryable,
  type FailureKind,
  type LocalCode,
  type TuiCode,
} from "./errors.js";
export { endpointPath, normalizeBaseUrl } from "./http.js";
export {
  EM_DASH,
  MASKED,
  UNLIMITED,
  bytes,
  dash,
  dayGroupLabel,
  duration,
  ellipsis,
  fitTo,
  isoOrNull,
  maskToken,
  onOff,
  padToWidth,
  percent,
  uptime,
  widthOf,
  type Align,
} from "./format.js";
export {
  COLUMN_GAP,
  DEFAULT_MIN,
  planColumns,
  type CellValue,
  type ColumnPlan,
  type ColumnSpec,
  type ColumnWidth,
  type PlanRow,
  type PlannedColumn,
} from "./columns.js";
export {
  BORDER_COLUMNS,
  BORDER_LEFT_COLUMN,
  BORDER_ROWS,
  MAIN_MIN_WIDTH,
  MAIN_TEXT_X,
  MENU_MIN_WIDTH,
  MENU_PAD_X,
  MENU_ROWS,
  MIN_TERMINAL_COLUMNS,
  MODEL_STATUS_ROWS,
  NOTICE_ROWS,
  PALETTE_MAX_RATIO,
  PROMPT_COLUMNS,
  SESSION_CLOSE_COLUMNS,
  SESSION_GAP_ROWS,
  SESSION_MARK_COLUMNS,
  SESSION_ROWS,
  SESSION_STRIDE,
  SIDEBAR_CLOSE_MIN_NAME,
  SIDEBAR_GAP,
  SIDEBAR_MAX_WIDTH,
  SIDEBAR_MIN_WIDTH,
  SIDEBAR_TEXT_X,
  SIDEBAR_TOP_PAD_ROWS,
  SIDEBAR_WIDTH,
  STATUS_LINE_HEIGHT,
  WINDOW_CLOSE_COLUMNS,
  WINDOW_CLOSE_INSET,
  WINDOW_HEADER_INDENT,
  WINDOW_INPUT_PROMPT_COLUMNS,
  WINDOW_PADDING,
  caretFromColumn,
  caretFromWrappedPoint,
  caretRowOf,
  geometry,
  hitTest,
  sidebarWidthBounds,
  wrapInput,
  type Geometry,
  type GeometryInput,
  type MenuRequest,
  type Rect,
  type WindowSlot,
  type WrappedRow,
} from "./geometry.js";
export {
  caretAtFirstRow,
  caretAtLastRow,
  caretDown,
  caretUp,
  deleteSelection,
  historyNext,
  historyPrev,
  insertNewline,
  normalizeSelection,
  pushHistory,
  replaceSelection,
  type HistoryStep,
  type Selection,
} from "./editor.js";
export {
  caretLeft,
  caretRight,
  deleteAt,
  deleteBefore,
  insertAt,
  isControlChar,
  printableOnly,
} from "./input-line.js";
export { describe, droppedHint, idOfName, readLedgerSafe, rowsOfFailure } from "./failures.js";
export {
  append,
  clampTop,
  dropped,
  flatten,
  maskEcho,
  rowsOfTurn,
  trim,
  visibleLines,
  type FlatLog,
  type LogEntry,
  type LogLine,
  type LogRow,
  type LogTone,
  type Turn,
} from "./log/index.js";